# ----
# Site

title: Home
url: "https://i7.pages.gitlab.lrz.de/dtcontrol"
baseurl:
google_analytics_key:
show_full_navigation: true

# Build

timezone: Europe/Berlin

permalink: pretty

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# collections:
#   docs:
#     title: Documentation
#     permalink: /:path/
#     output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
