image: gitlab.lrz.de:5005/i7/dtcontrol:1.4

stages:
  - test

Test:
  stage: test
  script:
    - /usr/bin/python3.7 --version
    - pwd
    - export PYTHONPATH="$(pwd):$(pwd)/dtcontrol:$PYTHONPATH"
    - /usr/bin/python3.7 -m unittest discover -s test
    - /usr/bin/python3.8 --version
    - pwd
    - export PYTHONPATH="$(pwd):$(pwd)/dtcontrol:$PYTHONPATH"
    - /usr/bin/python3.8 -m unittest discover -s test
