image: gitlab.lrz.de:5005/i7/dtcontrol:1

stages:
  - build

Build:
  stage: build
  script:
    - /usr/bin/python3 --version
    - PYTHONPATH="$(pwd):$PYTHONPATH" /usr/bin/python3 setup.py install
    - PYTHONPATH="$(pwd):$PYTHONPATH" /usr/bin/python3 dtcontrol/cli.py
