image: gitlab.lrz.de:5005/i7/dtcontrol:1.4

stages:
  - test

test:python3.7:
  stage: test
  script:
    - /usr/bin/python3.7 --version
    - pwd
    - /usr/bin/python3.7 -m unittest discover -s test
  artifacts:
    name: "$CI_JOB_NAME-Python3.7"
    when: on_failure
    expire_in: '20 min'
    paths:
      - decision_trees/

test:python3.8:
  stage: test
  script:
    - /usr/bin/python3.8 --version
    - pwd
    - /usr/bin/python3.8 -m unittest discover -s test
  artifacts:
    name: "$CI_JOB_NAME-Python3.8"
    when: on_failure
    expire_in: '20 min'
    paths:
      - decision_trees/