stages:
  - test
  - version
  - build

test:python3.7:
  image: gitlab.lrz.de:5005/i7/dtcontrol:1.6
  stage: test
  script:
    - /usr/bin/python3.7 --version
    - pwd
    - /usr/bin/python3.7 -m unittest discover -s test
  artifacts:
    name: "$CI_JOB_NAME-Python3.7"
    when: on_failure
    expire_in: '20 min'
    paths:
      - decision_trees/

test:python3.8:
  image: gitlab.lrz.de:5005/i7/dtcontrol:1.6
  stage: test
  script:
    - /usr/bin/python3.8 --version
    - pwd
    - /usr/bin/python3.8 -m unittest discover -s test
  artifacts:
    name: "$CI_JOB_NAME-Python3.8"
    when: on_failure
    expire_in: '20 min'
    paths:
      - decision_trees/

version:
  image: gitlab.lrz.de:5005/i7/dtcontrol:1.5
  stage: version
  script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan gitlab.lrz.de >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$CI_GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - python3.7 gen-semver.py
  artifacts:
    paths:
      - VERSION
  only:
    - master

gen:
  image: gitlab.lrz.de:5005/i7/dtcontrol:1.5
  stage: build
  script:
    - python3.7 setup.py bdist_wheel
    - python3.8 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
  only:
    - master

jekyll:
  stage: build
  image: ruby:2.7
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - web/vendor/ruby
  before_script:
    - apt update && apt install -y rsync
    - cd web
    - bundle config set path 'vendor/ruby'
    - bundle install
  script:
    - bundle exec jekyll build
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -avz _site/* ashok@vmesparza11:/var/www/dtcontrol
  only:
    - master