image: gitlab.lrz.de:5005/i7/dtcontrol:1.1

stages:
  - test

Test:
  stage: test
  script:
    - /usr/bin/python3 --version
    - export PYTHONPATH="$(pwd):$(pwd)/dtcontrol:$PYTHONPATH"
    - cd dtcontrol
    - /usr/bin/python3 -m unittest discover -s test
    # - PYTHONPATH="$(pwd):$PYTHONPATH" /usr/bin/python3 setup.py install
