# Preset Configurations
system-presets:
  default:
    determinize: none
    predicates: ['axisonly']
    impurity: 'entropy'
    safe-pruning: False
  qest19-sos:
    determinize: none
    predicates: ['axisonly']
    impurity: 'entropy'
    safe-pruning: True
  qest19-vik:
    determinize: none
    predicates: ['axisonly', 'linear-logreg']
    impurity: 'auroc'
    safe-pruning: False
